routes/web.php
<?php
require_once "auth.php";

Route::middleware(['auth'])->group(function () {

    Route::get("incidencias_civiles", "DashboardController@indexDashboardRegistroIncidencias")
        ->name('registro_incidencias');

    Route::get("controlpatrullas", "DashboardController@indexDashboardPatrullas")
        ->name('control_patrullas');

    Route::post('incidencias_civiles', "IncidenciaCivilController@store")
        ->name('incidencias_civiles.store');

//    Route::get("incidenciaspoliciales", "DashboardController@indexIncidenciasPoliciales")
//        ->name('incidencias_policiales');


    Route::get('/', function () {
        return view ('home');
    });

    Route::get('api/unidades_fuera_de_rango', 'UnidadController@obtenerUnidadesFueraDeSector');
    Route::get('api/unidades_para_incidente', 'UnidadController@unidadesParaIncidente');
    Route::get('api/sectores', 'SectorController@getSectores');
    Route::get('api/modelos', 'ModeloController@getModelos');
    Route::post('api/unidad_incidente', 'IncidenciaCivilController@asignarUnidad');
    Route::post('api/mensajes', 'MensajeController@store');
    Route::post('api/locations_snapped', 'HubLocalizacionController@getEvenlySpacedLocationsSnapped');
    Route::post('api/mensajes_leidos', 'MensajeController@marcarComoLeido');

    Route::post('api/incidencias_civiles_estado', 'IncidenciaCivilController@changeStatus');
    Route::get('api/incidencias_civiles/{id}', 'IncidenciaCivilController@getIncidencia');

    Route::resource('oficiales', 'OficialController');
    Route::resource('unidades', 'UnidadController');

    Route::get('incidencias', 'IncidenciaCivilController@index');

    Route::get('incidencias/{id}', 'IncidenciaCivilController@show');

    Route::get('configurar_hubs', 'HubConfigController@index')->name('hub_config');
    Route::post('configurar_hubs', 'HubConfigController@store')->name('hub_config.store');

    Route::prefix('reportes')->group( function () {
        Route::get('crimen', 'ReporteCrimenController@index')->name('reportes.crimen');
    });

});

Route::get("test", function () {
    $uni = \App\Models\Unidad::find(1);
    $uni->last_update_time = \Carbon\Carbon::now()->subMinutes(5);
    $uni->save();
    broadcast(new \App\Events\UnidadLastUpdate($uni,
        \App\Models\Destacamento::find(1)->id));
});

Route::get("formtest", function () {
    return view('formtest',[
            'breadCrumbs' =>
                [
                    ['text' => 'Recurso', 'link' => '/recurso'],
                    ['text' => 'Crear', 'link' => '/crear','active' => true,]
                ]
        ]
    );
});

resources/views/oficiales/create.blade.php
@extends('layouts.main')
@section('title', 'Registro de Oficiales')
@section('styles')

@endsection
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @component('components.formPanel', ['heading' => 'Registro de Oficiales'])
                @slot('body')

                    <form action="{{route('oficiales.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="row">
                            <div class="col-xs-6">
                                @component('components.input',[
                                    'title' => 'Nombre',
                                    'name' => 'nombre'
                                    ])
                                @endcomponent
                            </div>
                            <div class="col-xs-6">
                                @component('components.input',[
                                   'title' => 'Apellido',
                                   'name' => 'apellido'
                                   ])
                                @endcomponent
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6">
                                @component('components.input',[
                                    'title' => 'Fecha de nacimiento',
                                    'name' => 'fecha_nacimiento',
                                    'type' => 'date'
                                    ])
                                @endcomponent
                            </div>
                            <div class="col-xs-6">
                                @component('components.input',[
                                    'title' => 'Fecha de ingreso',
                                    'name' => 'fecha_ingreso',
                                    'type' => 'date'
                                    ])
                                @endcomponent
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6">
                                @component('components.input',[
                                    'title' => 'Cédula',
                                    'name' => 'cedula',
                                    'type' => 'text',
                                    'id' => 'cedula',
                                    'help' => 'Formato: XXX-XXXXXXX-X'
                                    ])
                                @endcomponent
                            </div>
                            <div class="col-xs-6">
                                @component('components.select',[
                                    'title' => 'Sexo',
                                    'name' => 'sexo'
                                    ])
                                    <option @if (old('sexo') == '0') selected @endif value="0">Masculino</option>
                                    <option value="1">Femenino</option>
                                @endcomponent
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6">
                                @component('components.select',[
                                   'title' => 'Rango',
                                   'name' => 'rango_id',
                                        'search' => true
                                   ])
                                    @foreach($rangos as $r)
                                        <option @if( old('rango_id') == $r->id) selected @endif
                                        value="{{$r->id}}">{{$r->nombre}}</option>
                                    @endforeach
                                @endcomponent
                            </div>
                            <div class="col-xs-6">
                                @component('components.select',[
                                    'title' => 'Tipo',
                                    'name' => 'tipo_oficial_id',
                                    'search' => true
                                    ])
                                    @foreach($tipos as $t)
                                        <option @if( old('tipo_oficial_id') == $t->id) selected @endif
                                        value="{{$t->id}}">{{$t->nombre}}</option>
                                    @endforeach
                                @endcomponent
                            </div>
                        </div>
                        @component('components.formButton')@endcomponent
                    </form>
                @endslot
            @endcomponent
        </div>
    </div>

@endsection
@section('scripts')
    <script>
      $('#cedula').formatter({
        'pattern': '@{{999}}-@{{9999999}}-@{{9}}',

      });
    </script>
@endsection